Добавляет страницу просмотра поста и сортировку постов
htmlacademy-php/1704585-readme-12 pull request #10
Opened 2021-05-18 20:23 UTC by HappyChel

Проблему с ссылкой так и не решил.
И еще не понял как возвращать ответ сервера 404.

2021-05-19 21:27 UTC, dmekhov commented
Что бы заработали ссылки сортировки нужно временно закомментировать js скрипты в основном лейауте: https://github.com/htmlacademy-php/1704585-readme-12/blob/master/templates/layout.php#L173

`<!--<script src="js/main.js"></script>-->`

в следующих заданиях они снова понадобятся, и сортировка будет меняться без перезагрузки страницы, поэтому тут реализация сортировки делается по желанию.  
Если делаешь сортировку - то в коде нужно учитывать выбранный фильтр по типу контента. т.е. переключение сортировки `order_by=1` не должно сбрасывать фильтр по типу `id=8`, должно получиться: `id=8&order_by=1`

2021-05-19 21:28 UTC, dmekhov commented
Возвращаемый код ответа управляется с помощью функции `http_response_code` (https://www.php.net/manual/ru/function.http-response-code.php)

https://up.htmlacademy.ru/php/12/module/6/item/1#ustanovka-koda-otveta

2021-05-19 22:19 UTC, dmekhov requested changes
В целом все хорошо, молодец!

Есть пара замечаний, и ответ на твой вопрос

2021-05-19 22:19 UTC, dmekhov commented on templates/main.php
> +                                    <?php if(!$id): ?> filters__button--active <?php endif; ?>" href="/">
Вместо if открывающего и закрывающего можно использовать чуть более компактную запись `<?= is_null($id) ? 'filters__button--active' : '' ?>`. В дальнейшем, при использовании шаблонизаторов вероятнее будет использоваться именно такой подход.

Отдельно отмечу - необходимость выполнять тут проверку на null, а не булево `!0` тут выполняется неявное приведение 0 к false. Лучше избегать таких конструкций.
Кроме того это противоречит дополнительному критерию [Д1](https://up.htmlacademy.ru/php/12/criteries#d1). Используется явное приведение типов в операциях с разными типами данных.

2021-05-19 22:19 UTC, dmekhov commented on post.php
> +    if(!mysqli_query($db_link, "SELECT id FROM posts WHERE id = $id")) {
Даже если в БД нет нужной записи - запрос тебе вернет пустой объект `mysqli_result`

Тут следует проверять что к-во строк в результате равно 0, например используя функцию `mysqli_num_rows` (https://www.php.net/manual/ru/mysqli-result.num-rows.php)

2021-05-19 22:19 UTC, dmekhov commented on post.php
> +    if($id){
Лучше проверять наличие id до выполнения sql запроса. Что бы не делать зря запрос в БД с 0 id.

В случае отсутствия id нужно возвращать 404 ошибку.

2021-05-19 22:19 UTC, dmekhov commented on post.php
> +    'post' => $post[0],
Рекомендация: Вместо того что бы обращаться к нулевому элементу массива с результатами, ты можешь доработать свою хелпер функцию `make_select_query`, так что бы она принимала значение `$one = true/false`

и в случае когда ты хочешь получить один элемент - использовать `mysqli_fetch_assoc` вместо  `mysqli_fetch_all`

2021-05-20 18:41 UTC, HappyChel commented on templates/main.php
> +                                    <?php if(!$id): ?> filters__button--active <?php endif; ?>" href="/">
Заменить на конструкцию <?= is_null($id) ? 'filters__button--active' : '' ?> не получилось. Возникли неполадки с типами!
Параметры запроса id и order_by имеют тип 'string' - в этом случае все работает. А попытка привести их к int ломают всю логику работы и соответственно компактная запись не срабатывает!

2021-05-20 20:22 UTC, dmekhov commented on templates/main.php
> +                                    <?php if(!$id): ?> filters__button--active <?php endif; ?>" href="/">
Погоди, я конкретно про случай с активной кнопкой "все".

Там у тебя id - не заполнен, а значит null. И вот тут можно делать проверку на is_null($id) как раз

2021-05-20 20:31 UTC, dmekhov approved these changes
Пара мелких замечаний, исправь в следующем задании

Принимаю!

2021-05-20 20:31 UTC, dmekhov commented on templates/main.php
> +                            href="/?<?=http_build_query(array_merge($_GET, ['id' => 0])); ?>">
Сейчас при выборе пункта все ты получаешь ссылку http://localhost:8081/?id=0

что бы исключить параметр при построении ссылки - ему нужно задать значение null `['id' => null]`

2021-05-20 20:31 UTC, dmekhov commented on helpers.php
> +        } else {
Тут можно без else

2021-05-20 20:31 UTC, merged