Отправка сообщений
htmlacademy-php/1704585-readme-12 pull request #16
Opened 2021-06-14 20:55 UTC by HappyChel

Возникли проблемы с отправкой почты. В чем проблема понять не могу!

И еще в личных сообщениях не могу сообразить как составить SQL запрос, чтобы при получении списка пользователей к каждому пользователю из списка привязать последнее сообщение из переписки?

2021-06-16 18:41 UTC, dmekhov commented
> Возникли проблемы с отправкой почты. В чем проблема понять не могу!

Судя по всему указанный для отправки сервер не работает

Ты можешь зарегать временную учетку на http://mailtrap.io/ или использовать smtp параметры любого бесплатного почтового сервиса

Еще можно использовать локальный сервис для перехвата сообщений https://github.com/maildev/maildev (для его настройки нужен node.js либо docker)

Тем не менее, я проверил. При подписке на пользователя - сообщение отправляется, все ок (ну почти)

![Снимок экрана от 2021-06-16 21-40-15](https://user-images.githubusercontent.com/15914658/122274669-7aee3500-ceeb-11eb-851c-bc520e43f008.png)

ссылку на профиль забыл добавить

2021-06-16 19:09 UTC, dmekhov requested changes

2021-06-16 19:09 UTC, dmekhov commented on add.php
> +                    $send_result = $mailer->send($message);
Ты в цикле отправляешь сообщение каждому пользователю

При этом накапливаешь в массиве $recipient все больше и больше полуателей

воспроизведи такой сценарий:  

добавь несколько подписчиков на себя, создай пост, посмотри что будет в массиве $recipient после foreach цикла  
(на первом шаге там будет email первого полуателя, на втором оба - и они оба получат письмо адресованное второму, на третьем все трое получат письмо с обращением к третьему по имени и т.д.)

2021-06-16 19:50 UTC, dmekhov commented
> И еще в личных сообщениях не могу сообразить как составить SQL запрос, чтобы при получении списка пользователей к каждому пользователю из списка привязать последнее сообщение из переписки?

тут два варианта:

первый - в лоб, сделать в цикле запрос за каждым последним сообщением для каждого пользователя (с limit 1)

второй более эффективный, но более сложный. можно используя конструкцию mysql if в селекте - выбрать пользователя с которым состоится переписка: https://dev.mysql.com/doc/refman/8.0/en/flow-control-functions.html#function_if  
и получить все контакты пользователя но ты получишь все сообщения отправленные или полученные пользователями и отсортировать результат по дате создания сообщения от большего к меньшему

затем тебе все равно нужно будет сделать проверку что указанный контакт уже учтен (брать только первое вхождение для каждого контакта)

можно расширить этот запрос и взять последние сообщения, по максимальной дате https://ru.stackoverflow.com/questions/663579/%d0%9f%d0%be%d0%bb%d1%83%d1%87%d0%b5%d0%bd%d0%b8%d0%b5-%d1%81%d1%82%d1%80%d0%be%d0%ba%d0%b8-%d1%81-%d0%bc%d0%b0%d0%ba%d1%81%d0%b8%d0%bc%d0%b0%d0%bb%d1%8c%d0%bd%d1%8b%d0%bc-%d0%b7%d0%bd%d0%b0%d1%87%d0%b5%d0%bd%d0%b8%d0%b5%d0%bc/663590#663590
выполнив join по условию contact + max_date - но тут уже придется повозиться

В целом, я бы сказал что для тестового проекта должно быть достаточно и первого варианта запроса - в лоб

2021-06-17 21:05 UTC, dmekhov requested changes
Уже близко!

Если уж взялся делать задачу с сообщениями - то давай добьем ;)

2021-06-17 21:05 UTC, dmekhov commented on helpers.php
> +            $result_string .= "</p>" . '<a class="post-text__more-link" href="#">Читать далее</a>';
Вообще, я бы положил ссылку в отдельную переменную, типа `$tail` (хвост)

И сделал проверку на is_simple один раз в перед возвратом
```
if($is_simple) {
 return $result_string
}

return "<p>$result_string</p>  $tail"
```
что-то вроде того.

А-то у тебя три раза одно и тоже условие проверяется.

2021-06-17 21:05 UTC, dmekhov commented on mail.php
> +$transport->setPassword('9c2208d64a0524');
Лучше не хранить в репозитории реквизиты доступа к внешним сервисам. (да и к внутренним, типа проля к БД и пр - тоже лучше не хранить)

2021-06-17 21:05 UTC, dmekhov commented on messages.php
> +                ) AS us ON mes.published_at = us.max_date
Почти ;)

Добавь несколько сообщений отправленных в одно и тоже время, вплоть до секунды.

В чате выводятся дубли, и контент не соответствует переписке

ты тут строишь join только по полю published_at не смотря на то что это поле может быть одинаковым у разных сообщений.

Нужна еще проверка на получателя/отправителя.

2021-06-17 21:26 UTC, HappyChel commented on mail.php
> +$transport->setPassword('9c2208d64a0524');
Это я понимаю,  но как это правильно использовать не знаю. В учебных материалах я с этим не сталкивался. Как стоит делать?

2021-06-18 07:11 UTC, dmekhov commented on mail.php
> +$transport->setPassword('9c2208d64a0524');
В больших проектах для этого используются `.env` конфигурации (dotenv)

Но пока, можно просто создать файл `local_config.php` - добавить его в `.gitignore`  
И подключить его к проекту, с проверкой file_exists('local_config.php')

По хорошему при такой схеме - локальный конфиг должен дополнять (переопределять) дефолтные значения конфигурации. т.е. в  общем конфиге должны быть указаны все нужные переменные что ты описываешь в local_config, но значения в дефолтном должны быть либо стандартные (localhost, phpdemo и пр), либо пустые. Но другой разработчик скачавший твой проект должен знать какие переменные ему нужно описать в своей версии локального конфига.

А самым простым топорным решением - просто закоммитить левый пароль, в файле, а локально прописывать нужный, не забывая убирать файл при коммите (но это чисто временное решение только для учебного проекта)

2021-06-19 09:47 UTC, dmekhov commented on mail.php
> +$transport->setPassword('9c2208d64a0524');
Принимаю.
Но перед сдачей на проверку нужно добавить дефолтный конфиг.
Сейчас разработчик скачавших твой проект (и проверяющий) не имея локального конфига - не будет знать какие параметры ему нужно указать в своем конфиге.

По факту нужен ещё один файл в который будет инклюдиться локальный и там в нужные переменные будут вставляться значения из локального либо дефолтное при его отсутствии.

Типа: `$db_user = $local_db_user ?? 'root'`

2021-06-19 09:47 UTC, merged