Добавляет функцию, которая обрезает текстовое содержимое поста
htmlacademy-php/1704585-readme-12 pull request #4
Opened 2021-05-03 16:00 UTC by HappyChel

2021-05-03 18:33 UTC, dmekhov requested changes
Общий подход верный.  

Но нужно исправить определение длинны строки (а заодно и пару мелочей).

2021-05-03 18:33 UTC, dmekhov commented on index.php
> +        $result_string = $result_string . implode(" ", $result_array) . "...</p>";
Ты ниже используешь конструкцию `$result_string .=`, а тут нет почему-то, действительно удобная запись.

Тоже касается и 57 строки

2021-05-03 18:33 UTC, dmekhov commented on index.php
> +        $result_string = $result_string . implode(" ", $result_array) . "...</p>";
В условии задачи про это ничего нет, но все же рекомендую дополнить (не всегда описание задачи будет пошагово объяснять что от тебя требуется некоторые пограничные условия нужно додумывать самому):

если у тебя строка закончится точкой, в итоге ты получишь .... четыре точки в конце

Тебе поможет функция trim: https://www.php.net/manual/ru/function.trim.php

2021-05-03 18:33 UTC, dmekhov commented on index.php
> +    if (strlen($string) > $length){
Сравни вывод двух значений:  
`var_dump('zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz')`  
`var_dump('яяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяя')`

В текущей реализации, у тебя preview поста будет в два раза короче, чем ожидается.

Все дело в том что русские символы (как и многие другие не латинские) записываемые в utf8 кодировке, кодируются не одним байтом, а двумя (обычно, в некоторых случаев может быть три, а иногда и четыре). При работе с не латинским текстом следует использовать функции предназначенные для работы с мультибайтовыми строками. Они обычно имеют префикс `mb_`. https://www.php.net/manual/ru/ref.mbstring.php
В данном случае, тебе нужна `mb_strlen`. Также и при определении длинны слова.

2021-05-03 20:08 UTC, HappyChel commented on index.php
> +        $result_string = $result_string . implode(" ", $result_array) . "...</p>";
В данном случае у меня возникает вопрос: только ли для точки это справедливо или необходимо отрезать и другие символы, такие как , ! ? : ; и т.п.?

2021-05-03 20:40 UTC, dmekhov commented on index.php
> +        $result_string = $result_string . implode(" ", $result_array) . "...</p>";
Хороший вопрос, правильный :+1: 

С учетом того что в условии задачи этого не указано, решение остается за тобой.  
Ты можешь перечислить в списке вырезаемых значений несколько символов `.,!?:;`, можешь оставить только точку

Кстати правильней будет использовать `rtrim`, а не просто `trim`, тогда обрезать мы будем строку только справа.

Вообще, в дальнейшем для этой цели можно будет использовать регулярные выражения, которые найдут в строке любые символы не являющиеся буквами, например. https://www.php.net/manual/ru/function.preg-replace.php  
Но если ты раньше с таким не сталкивался - то пока даже не открывай эту ссылку. Можешь записать себе куда-то в план по изучению, после курса.

2021-05-04 18:30 UTC, dmekhov approved these changes
:+1:

2021-05-04 18:30 UTC, dmekhov commented on index.php
> +        do {
Твоя функция работает, и подходит по условию, поэтому принимаю

Но вариант с foreach вероятно проще, с точки зрения к-ва проверок которые нужно держать в голове
(можно было просто пройтись в foreach цикле по всем $words, и прервать выполнение break в случае если итоговая строка получается больше переданного ограничения. и вручную за счетчиком не нужно следить.)

2021-05-04 18:31 UTC, merged